function opts = setting_lcnt_iccv2019_post(opts, numRegions)

    opts = lcnt_get_opts('verbose', opts.verbose, 'useGpu', opts.useGpu, ...
                         'netPath', opts.netPath, 'isDagNN', true, ...
                         'normalize', true, 'headType', 'amrconv', ...
                         'MaskSize', 5, 'downsamplingFactor', 2, ...
                         'searchPadding', 3.5, 'warmupTimes', 5, ...
                         'projectInDims', 96, 'projectOuDims', 48, ...
                         'alpha', 0.8, 'inputShape', 'square', ... 
                         'maxTargetSize', 75, 'minTargetSize', 45, ...
                         'motionSigmaFactor', 0.23, 'FIFO', true, ...
                         'scaleLr', 0.8, 'numScales', 3, ...
                         'scaleStep', 1.02, ... tracking settings ...
                         'initMaxIters', 150, 'initMinIters', 100, ...
                         'updateMaxIters', 5, 'initLr', 1e-5, ...
                         'updateLr', 1e-5/2, 'outputSigmaFactor', 1/10, ...
                         'numRegions', numRegions);

    opts.state_initialize = @lcnt_state_initialize;
    opts.state_warmup = @lcnt_warmup;
    opts.initialize = @lcnt_initialize;
    opts.track = @lcnt_track;
    opts.update = @lcnt_update;
    opts.release = @lcnt_release;
                        
end

