function opts = setting_lcnt_default(opts, numRegions)

    opts = lcnt_get_opts('verbose', opts.verbose, 'useGpu', opts.useGpu, ...
                         'netPath', opts.netPath, 'isDagNN', true, ...
                         'normalize', true, 'headType', 'amrconv', ...
                         'downsamplingFactor', 2, ...
                         'searchPadding', 3.5, 'warmupTimes', 5, ...
                         'projectInDims', 96, 'projectOuDims', 48, ...
                         'maxTargetSize', 75, 'minTargetSize', 45, ...
                         'motionSigmaFactor', 0.23, ...
                         'scaleLr', 0.8, 'numScales', 3, ...
                         'scaleStep', 1.02, ... tracking settings ...
                         'initMaxIters', 150, 'initMinIters', 100, ...
                         'updateMaxIters', 5, 'initLr', 1e-5, ...
                         'updateLr', 6e-6, 'outputSigmaFactor', 1/10, ...
                         'numRegions', numRegions);

    opts.state_initialize = @lcnt_state_initialize;
    opts.state_warmup = @lcnt_warmup;
    opts.initialize = @lcnt_initialize;
    opts.track = @lcnt_track;
    opts.update = @lcnt_update;
    opts.release = @lcnt_release;
                     
    % better than CVPR submissions
%           opts = lcrt_get_opts('verbose', opts.verbose, 'useGpu', opts.useGpu, ...
%                          'netPath', opts.netPath, 'isDagNN', true, ...
%                          'normalize', true, 'headType', 'maskconv', ...
%                          'MaskSize', 5, 'downsamplingFactor', 2, ...
%                          'searchPadding', 3.5, 'warmupTimes', 5, ...
%                          'projectInDims', 96, 'projectOuDims', 48, ...
%                          'alpha', 0.8, 'inputShape', 'proportional', ... 
%                          'maxTargetSize', 75, 'minTargetSize', 45, ...
%                          'motionSigmaFactor', 0.68, 'FIFO', true, ...
%                          'scaleLr', 0.8, 'numScales', 3, ...
%                          'scaleStep', 1.02, ... tracking settings ...
%                          'initMaxIters', 150, 'initMinIters', 100, ...
%                          'updateMaxIters', 5, 'initLr', learningRate, ...
%                          'updateLr', learningRate, 'outputSigmaFactor', 1/10);

    % 8e-6 for normal settings
%     opts.state_initialize = @lcrtnew_state_initialize;
%     opts.state_warmup = @lcrtnew_warmup;
%     opts.initialize = @lcrtnew_initialize;
%     opts.track = @lcrtnew_track;
%     opts.update = @lcrt_update;
%     opts.release = @lcrtnew_release;
   
end

