function opts = setting_lcrt_forfun(opts)

    opts = lcrt_get_opts('verbose', opts.verbose, 'useGpu', opts.useGpu, ...
                         'netPath', opts.netPath, 'isDagNN', true, ...
                         'normalize', true, 'headType', 'maskconv', ...
                         'MaskSize', 5, 'downsamplingFactor', 2, ...
                         'searchPadding', 3.5, 'warmupTimes', 5, ...
                         'projectInDims', 96, 'projectOuDims', 48, ...
                         'alpha', 0.8, 'inputShape', 'proportional', ... 
                         'maxTargetSize', 75, 'minTargetSize', 45, ...
                         'motionSigmaFactor', 0.68, 'FIFO', true, ...
                         'scaleLr', 0.8, 'numScales', 3, ...
                         'scaleStep', 1.02, ... tracking settings ...
                         'initMaxIters', 150, 'initMinIters', 100, ...
                         'updateMaxIters', 5, 'initLr', 1e-5, ...
                         'updateLr', 8e-6, 'outputSigmaFactor', 1/10); 

   
    opts.state_initialize = @lcrtnew_state_initialize;
    opts.state_warmup = @lcrtnew_warmup;
    opts.initialize = @lcrtnew_initialize;
    opts.track = @lcrtnew_track;
    opts.update = @lcrt_update;
    opts.release = @lcrtnew_release;
   
end

