function state = base_update(state, img)
    if(mod(state.currFrame, state.oparams.intervals)==0 )
        trainFeatrs = cat(4, state.trainFeatrs{:});
        trainLabels = cat(4, state.trainLabels{:});

        [state.net_h, state.trainState] = ...
            lcrt_finetune(state.net_h, trainFeatrs, trainLabels, ...
                          state.trainState, state.oparams, ...
                          'maxIters', state.oparams.updateMaxIters, ...
                          'learningRate', state.oparams.updateLr, ...
                          'verbose', state.oparams.verbose);

    end
end

